=== letmechek/mulesoft/new2/covid/src/main/resources/schemass/jsonschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "source": {
      "type": "string"
    },
    "casetype": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "dateOfBirth": {
      "type": "string"
    },
    "nationalID": {
      "type": "string"
    },
    "nationalIDType": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "postal": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "street",
        "city",
        "state",
        "postal",
        "country"
      ]
    }
  },
  "required": [
    "source",
    "casetype",
    "firstName",
    "lastName",
    "phone",
    "dateOfBirth",
    "nationalID",
    "nationalIDType",
    "address"
  ]
}

=== letmechek/mulesoft/new2/covid/src/main/resources/examples/covid.json
{
    "source": "hospital1",
    "casetype": "positive",
    "firstName": "John",
    "lastName": "Nixon",
    "phone": "546-524-3423",
    "email": "john@gmail.com",
    "dateOfBirth": "1989-04-26",
    "nationalID": "209-49-6193",
    "nationalIDType": "SSN",
    "address": {
        "street": "1600 West Mall St Blvd",
        "city": "Washington",
        "state": "DC",
        "postal": "20500",
        "country": "USA"
    }
}
